name: Go Generate, Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 17
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Generate
      run: go generate -v ./...
      working-directory: ./go
    - name: Build
      run: go build -v ./...
      working-directory: ./go
    - name: Test
      run: go test -v ./...
      working-directory: ./go

