name: Go Generate, Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 17
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Generate
      run: go generate -v ./...
      working-directory: ./go
    - name: Build
      run: go build -v ./...
      working-directory: ./go
    - name: Test
      run: go test -v ./...
      working-directory: ./go
    - name: Generate darwin/amd64
      working-directory: ./go
      run: env GOOS=darwin GOARCH=amd64 go build -o ../dist/darwin/amd64/ ./cmd/qtag
    - name: Generate darwin/arm64
      working-directory: ./go
      run: env GOOS=darwin GOARCH=arm64 go build -o ../dist/darwin/arm64/ ./cmd/qtag
    - name: Generate windows/amd64
      working-directory: ./go
      run: env GOOS=windows GOARCH=amd64 go build -o ../dist/windows/amd64/ ./cmd/qtag
    - name: Generate linux/amd64
      working-directory: ./go
      run: env GOOS=linux GOARCH=amd64 go build -o ../dist/linux/amd64/ ./cmd/qtag
    - name: Generate linux/arm64
      working-directory: ./go
      run: env GOOS=linux GOARCH=arm64 go build -o ../dist/linux/arm64/ ./cmd/qtag
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-without-markdown
        path: dist
